#!/usr/local/bin/python
# coding=utf-8
import os
import subprocess
import sys

def getapp():
    states = execute("adb shell dumpsys window | grep -E 'mCurrentFocus|mFocusedApp&Window' | cut -d' ' -f7")
    for state in states:
        state = state.strip()
        if state == "Error:":
            # 处理应用崩溃的时候
            print "state:" , state
            lines = execute("adb shell dumpsys window | grep -E 'mCurrentFocus|mFocusedApp&Window' | cut -d' ' -f8 | cut -d'}' -f1")
            for line in lines:
                line = line.strip()
                return line
        else:
            # 处理应用正常在前台的情况
            lines = execute("adb shell dumpsys window | grep -E 'mCurrentFocus|mFocusedApp&Window' | cut -d' ' -f6 | cut -d'/' -f 1")
            for line in lines:
                line = line.strip()
                return line

def execute(cmd):
    result = os.popen(cmd).readlines() 
    print cmd ," -->" ,result
    return result

app = getapp()
if app:
    cmd = ("adb uninstall %s" % app)
    execute(cmd)